### ISSUE TITLE
[Bug]: Entity names are “SolaX Inverter Inverter Inverter Inverter Inverter …”

### ISSUE THREAD

**Issue by freddanastrom** [wills106/homeassistant-solax-modbus#987]
### Describe the bug

After updating to 2024.08.7 all entities except the type sensor have the  “SolaX Inverter Inverter Inverter Inverter Inverter …” in the friendly names. Entity id’s seems to be correct.

All “sensor.” has the correct names.
“number.”, “button.”, “input.” etc has the inverter inverter inverter included in the names.

A lot of inverter inverter:
![IMG_0368](https://github.com/user-attachments/assets/a912500f-c465-4ee1-9c60-921c40991deb)

Example of entity with correct id, but wrong friendly name:
![IMG_0371](https://github.com/user-attachments/assets/3fadb9c7-f29b-474c-8460-e4d283a935ff)

### Integration Version

2024.08.7

### Homeassistant core version

2024.7.4

### Inverter brand

SolaX

### Plugin used

plugin_solax.py

### Serial prefix

H3BC25

### Inverter firmware versions

DSP 20 ARM 15.14

### Connection Method

Waveshare

### Dongle firmware

V1.452

**Comment by wills106** [comment]
Do you have multiple Inverters setup. Or just the one?

I know if you have two Inverters, the second one get's a single Inverter added to the front of the name.

But not experienced this on a single setup.

First mention was https://github.com/wills106/homeassistant-solax-modbus/issues/980#issuecomment-2271260169 but then the issue went https://github.com/wills106/homeassistant-solax-modbus/issues/980#issuecomment-2271832361

**Comment by freddanastrom** [comment]
Just one single inverter.
I also removed the integration prior to updating, as recommended in the release notes.

**Comment by freddanastrom** [comment]
Just noticed that 2024.08.8 was released while I was filling the form and updating to this version seems to solve this naming issue.

**Comment by LubikR** [comment]
@wills106 , @freddanastrom , I have tested this with new version 2024.08.8 and don't think that this issue is resolved. If you want add "Inverter" to entity names just reload the integration. Everytime you reload integration, new text "Inverter" is added

**Comment by wills106** [comment]
There wasn't any change between 2024.08.1 to 2024.08.8 to alter this behaviour.

So I think restarting HA reset it back to no added "Inverter"

I'll have a proper look into this over the next few days.

**Comment by freddanastrom** [comment]
Sorry for closing the issue before making sure updating was the solution.

I tried to reloading the integration a couple of times without any naming issues.

However, when editing the configuration I erased the name suffix option and saved it blank.
Suffix was still there when looking at the entity names.
Editing the settings once again and adding a suffix does as expected add a the suffix to the name, but also keeps the previous.
Repeat and get more added to the entity names.

**Comment by wills106** [comment]
> Sorry for closing the issue before making sure updating was the solution.

It's ok.

> However, when editing the configuration I erased the name suffix option and saved it blank.
> Suffix was still there when looking at the entity names.
> Editing the settings once again and adding a suffix does as expected add a the suffix to the name, but also keeps the previous.
> Repeat and get more added to the entity names.

That's handy to know then, when editing the config it seems to add all of the duplicates?

**Comment by MiJo112** [comment]
I still have the same bug with 2024.08.8. Every time I change the name, it is only added, the old one is not deleted.  I would like to do without the name Inverter completely
![image](https://github.com/user-attachments/assets/f983c590-69fa-4613-adab-48370ef011a9)
